[app]
name = "Asl to English Translator"
environment = "development"
width = "1280"
height= "800"

[api]
base_url = "http://localhost:8080"

[gestures]
gesture_model = "testing"

[settings]
examples = "5"
sam_rate = "16000"
init_chunk_der = "8.0"
min_chunk_der = "2.0"
chunk_dec = "1.0"